spring:
  datasource:
  url: jdbc:mysql://localhost:3306/academia?connectionTimeZone=UTC
  username: root
  password:
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
   